module.exports = {
	projects: [
		'<rootDir>/apps/hrhub',
		'<rootDir>/libs/layout',
		'<rootDir>/libs/session',
		'<rootDir>/libs/common',
		'<rootDir>/libs/dashboard',
		'<rootDir>/libs/employees',
		'<rootDir>/libs/navigation',
		'<rootDir>/libs/core-lib',
		'<rootDir>/libs/http',
		'<rootDir>/libs/config',
		'<rootDir>/libs/domain',
		'<rootDir>/libs/grid',
		'<rootDir>/libs/profile',
		'<rootDir>/libs/cv',
		'<rootDir>/libs/settings',
		'<rootDir>/libs/auth',
		'<rootDir>/libs/breadcrumbs',
		'<rootDir>/libs/platform',
		'<rootDir>/libs/user',
		'<rootDir>/libs/curtain',
		'<rootDir>/libs/tasks',
		'<rootDir>/libs/card',
		'<rootDir>/libs/tooltip-filter',
	],
};
